name: Tests

on:
  push:
    branches:
    - main
    - testing
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  deptest:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [1.2.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gh
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Test CLI
        run: |-
          fianu
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [1.3.0, 1.7.0, 1.7.1]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gh
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Test CLI
      run: |-
        fianu
